# Install Homebrew taps.
# Bundle: Used for installing dependencies from ~/.Brewfile.
# Cask: Used to install macOS applications distributed as binaries.
# Cask-Versions: Used to install alternate versions of Casks.
# Core: Used to install CLI applications.
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Install mas - a command line interface for installing Mac App Store apps.
brew "mas"

# Useful packages.
brew "git"
brew "nvm"
brew "pyenv"
brew "rbenv"
brew "wget"

# Bitcoin/altcoin development.
brew "automake"
brew "berkeley-db4"
brew "boost"
brew "help2man"
brew "libevent"
brew "librsvg"
brew "libtool"
brew "miniupnpc"
brew "openssl"
brew "pkg-config"
brew "protobuf"
brew "qrencode"
brew "qt"

# Install macOS applications distributed as binaries.
cask "cleanmymac"
cask "discord"
cask "dropbox"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "gpg-suite"
cask "imageoptim"
cask "keepingyouawake"
cask "ledger-live"
cask "mullvadvpn"
cask "plex-media-player"
cask "qbittorrent"
cask "riot"
cask "sdformatter"
cask "skype"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "tor-browser"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "wasabi-wallet"

# Install applications from the Mac App Store.
mas "1Password 7", id: 1333542190
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Reeder 4", id: 1449412482
mas "Spark", id: 1176895641
mas "Telegram", id: 747648890
mas "Xcode", id: 497799835
