###########
# Exports #
###########

# Use `ls` with colour output in accordance with Atom One Dark Terminal setup
# instructions.
# https://github.com/nathanbuchar/atom-one-dark-terminal#colors-not-working
export CLICOLOR=1
export LSCOLORS='ExFxBxDxCxegedabagacad'

###########
# Aliases #
###########

# Always enable coloured `grep` output.
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Colourised `ls` output.
alias ls='ls -G'

###########
# Options #
###########

## History ##

[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

# Record timestamp of command in HISTFILE
setopt EXTENDED_HISTORY

# Delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt HIST_EXPIRE_DUPS_FIRST

# Ignore duplicated commands history list
setopt HIST_IGNORE_DUPS

# Ignore commands that start with space
setopt HIST_IGNORE_SPACE

# Show command with history expansion to user before running it
setopt HIST_VERIFY

# Add commands to HISTFILE in order of execution
setopt INC_APPEND_HISTORY

# Share history between all sessions.
setopt SHARE_HISTORY

######################
# nvm, pyenv & rbenv #
######################

## nvm ##

# Set nvm directory location.
export NVM_DIR="$HOME/.nvm"

# This loads nvm.
[[ -s "/usr/local/opt/nvm/nvm.sh" ]] && \. "/usr/local/opt/nvm/nvm.sh"

# This loads nvm bash_completion.
[[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ]] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

## pyenv ##

# Check for pyenv and if available run the init script. Place towards the end of
# .zshrc because it manipulates PATH during the initialization.
which pyenv &>/dev/null && eval "$(pyenv init -)"

## rbenv ##

# Check for rbenv and if available run the init script. Place towards the end of
# .zshrc because it manipulates PATH during the initialization.
which rbenv &>/dev/null && eval "$(rbenv init -)"

################
# Prompt Theme #
################

# Add terminal-theme directory (where the Spaceship prompt theme is located) to
# $fpath.
fpath=($fpath "${HOME}/.zsh/themes")

# Only show the following prompt sections
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# Make '$' the prompt character shown before command input
SPACESHIP_CHAR_SYMBOL="$ "

# Always show the username, not just when it's different from $LOGNAME
SPACESHIP_USER_SHOW="always"

# Don't truncate folders in prompt
SPACESHIP_DIR_TRUNC=0

# Disable symbols that require the Powerline patched font.
SPACESHIP_DIR_LOCK_SYMBOL=""
SPACESHIP_GIT_SYMBOL=""

# Load the zsh prompt themes extension and set Spaceship as the prompt theme.
autoload -U promptinit && promptinit
prompt spaceship
