os: osx
stages:
    - lint
    - test
env:
    global:
        - TRAVIS_CI=1
jobs:
    include:
        # Lint stage
        - stage: lint
          language: bash
          install:
              - brew install shellcheck
          script:
              - shellcheck script/*.sh

        # macOS High Sierra (version 10.12)
        - stage: test
          osx_image: xcode9.2
          script:
              - ./script/install.sh -f

        # macOS High Sierra (version 10.13)
        - stage: test
          osx_image: xcode10
          script:
              - ./script/install.sh -f
