os: osx
stages:
  - lint
  - test
env:
  global:
    - CI=1
jobs:
  include:
    # Lint stage
    - stage: lint
      name: 'Lint'
      language: bash
      install:
        - brew install shellcheck
      script:
        - shellcheck install.sh
        - shellcheck script/*.sh

    # macOS High Sierra (version 10.13)
    - stage: test
      name: 'macOS 10.13 and Xcode 10.1'
      osx_image: xcode10.1
      script:
        - ./install.sh -f

    # macOS Mojave (version 10.14)
    - stage: test
      name: 'macOS 10.14 and Xcode 11.0'
      osx_image: xcode11
      script:
        - ./install.sh -f
