###########
# Exports #
###########

# ignoredups in Bash history causes lines matching the previous history entry to
# not be saved.
export HISTCONTROL="ignoredups"

#########
# Paths #
#########

remove_from_path() {
  [ -d "$1" ] || return
  # Doesn't work for first item in the PATH but I don't care.
  export PATH=${PATH//:$1/}
}

add_to_path() {
  [ -d "$1" ] || return
  remove_from_path "$1"
  export PATH="$1:$PATH"
}

quiet_which() {
  which "$1" &>/dev/null
}

# Add paths to PATH in reverse order.
add_to_path "/sbin"
add_to_path "/usr/sbin"
add_to_path "/usr/local/sbin"
add_to_path "/bin"
add_to_path "/usr/bin"
add_to_path "/usr/local/bin"

# Add gpg (via GPG Suite) to PATH if it exists. We check if the gpg binary
# exists in the GPG Suite bin folder so that it doesn't get confused with
# another installation of gpg which could happen if we used which.
if [[ -f /usr/local/MacGPG2/bin/gpg ]]; then
    add_to_path "/usr/local/MacGPG2/bin"
fi

# Add pyenv to PATH if it exists. We check with the 'which' command rather than
# checking if the directory exists in case pyenv has been uninstalled and
# folders were not removed in the process.
quiet_which pyenv && eval "$(pyenv init -)"

# Add rbenv to PATH if it exists. We check with the 'which' command rather than
# checking if the directory exists in case pyenv has been uninstalled and
# folders were not removed in the process.
quiet_which rbenv && eval "$(rbenv init -)"

###########
# Aliases #
###########

# Use GNU ls with color output for `ls`.
alias ls="gls --color"
alias sha256sum="gsha256sum"
alias sha512sum="gsha512sum"

# Always enable colored `grep` output.
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#########
# Misc. #
#########

# Use a modified Solarized Dark 256 color theme for the color GNU ls utility
eval "$(gdircolors $HOME/.terminal-theme/dircolors)"

# Load the Solarized Dark theme for the shell
source ~/.bash_prompt
