###########
# Exports #
###########

# Use `ls` with colour output in accordance with Atom One Dark Terminal setup
# instructions.
# https://github.com/nathanbuchar/atom-one-dark-terminal#colors-not-working
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

###########
# Aliases #
###########

# Always enable coloured `grep` output.
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

###########
# Options #
###########

# Write the history file in the ':start:elapsed;command' format.
setopt EXTENDED_HISTORY

# Write to the history file immediately, not when the shell exits.
setopt INC_APPEND_HISTORY

# Share history between all sessions.
setopt SHARE_HISTORY

# Expire a duplicate event first when trimming history.
setopt HIST_EXPIRE_DUPS_FIRST

# Do not record an event that was just recorded again.
setopt HIST_IGNORE_DUPS

# Delete an old recorded event if a new event is a duplicate.
setopt HIST_IGNORE_ALL_DUPS

# Do not display a previously found event.
setopt HIST_FIND_NO_DUPS

# Do not record an event starting with a space.
setopt HIST_IGNORE_SPACE

# Do not write a duplicate event to the history file.
setopt HIST_SAVE_NO_DUPS

# Do not execute immediately upon history expansion.
setopt HIST_VERIFY

# Append to history file.
setopt APPEND_HISTORY

# Don't store history commands.
setopt HIST_NO_STORE

######################
# nvm, pyenv & rbenv #
######################

# Set nvm directory location.
export NVM_DIR="$HOME/.nvm"

# This loads nvm.
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"

# This loads nvm bash_completion.
[[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"

# Check for pyenv and if available run the init script. Place towards the end of
# .zshrc because it manipulates PATH during the initialization.
which pyenv &>/dev/null && eval "$(pyenv init -)"

# Check for rbenv and if available run the init script. Place towards the end of
# .zshrc because it manipulates PATH during the initialization.
which rbenv &>/dev/null && eval "$(rbenv init -)"

################
# Prompt Theme #
################

# Add terminal-theme directory (where the Spaceship prompt theme is located) to
# $fpath.
fpath=( "$HOME/.dotfiles/terminal-theme" $fpath )

# Load the zsh prompt themes extension and set Spaceship as the prompt theme.
autoload -U promptinit; promptinit
prompt spaceship
